### ISSUE TITLE
Unable to adjust image

### ISSUE THREAD

**Issue by Mikoribbit** [505e06b2/Image-to-Braille#3]
It is more difficult to adjust the area where the picture should be displayed. Hope to add back the three RGB adjustment bars.

**Comment by 505e06b2** [comment]
> It is more difficult to adjust the area where the picture should be displayed

Could you give an example? I'm not sure what you mean

> Hope to add back the three RGB adjustment bars

In practice, they didn't seem to work very well. It's very possible that my algorithm was incorrect, but I don't feel having such precise control is very useful since it's almost essential to run the image through a bitmap editor to improve clarity

**Comment by gdSeraphim** [comment]
this new update make a huge problem to make good braille images... without the RGB, its very difficult to make good and precise images. 

(Before) RGB Control + Invert:
⠄⠄⠄⠄⠄⠄⠄⠄⢀⣴⠄⠄⠄⠄⢠⣿⣿⡆⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⢸⣿⣷⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄
⠄⠄⠄⠄⠄⠄⠄⣰⣿⡿⠄⠄⠄⢠⣿⣿⣿⣿⡄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⢸⣿⣿⡇⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄
⠄⠄⠄⠄⠄⢀⣴⣿⣿⠇⠄⠄⢠⣾⣿⣿⣿⣿⠇⠄⠄⠄⡄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠸⣿⣿⣧⠄⠄⠄⠄⡆⠄⠄⠄⠄⠄
⠄⠄⠄⠄⣠⣮⣭⣝⣛⠄⠄⠄⠛⢛⣛⣩⣭⣶⣾⣷⠄⠄⢸⡆⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⣰⣿⣾⣍⡛⠆⠄⠄⢰⣷⡀⠄⠄⠄⠄
⠄⠄⢀⣼⣿⣿⣿⣿⠇⣠⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣀⠄⢷⡀⠄⠄⠄⠄⠄⠄⠄⠄⠄⣸⣿⣿⣿⣿⣿⣿⠄⢀⣶⣶⡆⠄⠄⠄⠄
⢀⣴⣷⣿⣿⣿⣿⣧⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣤⢸⣵⠄⠄⠄⠄⠄⠄⠄⠄⣼⣿⣿⣿⣿⣿⣿⣿⠄⢸⣿⣿⣇⠄⠄⠄⠄
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣦⣍⠉⢻⣿⣿⣿⣿⣷⣿⣷⡀⠄⠄⠄⣰⠄⣴⣿⣿⣿⣿⣿⣿⣿⣿⣰⣿⣿⣿⣿⠄⠄⠄⠄
⣿⣿⣿⣿⣿⣿⣿⡿⠿⠛⠋⠉⠉⠉⠉⠛⠿⣿⣷⣽⣿⣿⣿⣿⣿⣿⣧⠄⣀⣴⣃⣼⣿⣿⡟⢁⣠⣶⠿⠿⠿⠿⣿⣿⣿⣿⠄⠄⠄⠄
⢿⣿⣿⣿⣿⢏⣽⡎⠄⠄⠄⠄⠄⠄⠄⠄⠄⣶⡽⣿⣿⣿⣿⣿⣿⣿⣿⣶⣿⣿⣿⣿⣿⣿⡷⠋⠄⠄⠄⠄⠄⠄⠸⣍⢿⣿⠄⠄⠄⠄
⢸⣿⣿⣿⠁⣾⣿⣇⠄⠄⠄⠄⠄⠄⠄⠄⠄⣿⣿⡘⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢳⡇⠄⠄⠄⠄⠄⠄⠄⣿⡿⣿⠄⠄⠄⠄
⠈⣿⣿⣿⣧⣻⣿⣯⣤⣶⣾⣿⣿⣿⣶⣦⣤⣛⣻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⣸⣷⣀⣤⣤⣤⣤⣄⡰⠿⢣⢋⠄⠄⠄⠄
⠄⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣏⣽⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣾⣿⣿⠄⠄⠄⠄
⠄⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⠄⠄⠄⠄
⠄⠄⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢿⣿⣿⣿⠁⠄⠄⠄⠄
⠄⠄⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠄⠄⠄⠄⠄
⠄⠄⠘⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠄⠄⣀⣀⡀
⠄⠄⠄⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⢋⣭⣷⣶⣿⣿⣿⣿
⠄⠄⠄⠄⢿⣿⣿⣿⣿⣿⣿⣏⣿⣦⣙⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡯⣟⣡⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿
⠄⠄⠄⠄⠘⢿⣿⣿⣿⣿⣿⣿⣜⠫⢛⣷⣭⣛⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⣽⣿⣿⢯⣴⣿⣿⣿⣿⠟⠅⢸⣿⣿⣿⣿⣿
⠄⠄⠄⠄⠄⠘⠻⣿⣿⣿⣿⣿⣿⣷⣮⡙⠿⣿⣷⣶⣿⣭⣍⣛⣛⠛⢛⣛⣛⣉⠍⣣⣶⣿⣿⢣⣾⣿⡿⠟⠋⠑⢀⠄⠈⢻⡿⢻⣿⣿
⠄⠄⠄⠄⠄⠄⠄⠄⠈⠻⢿⣿⣿⣿⣿⣿⣿⣶⣬⣉⣛⣛⣿⣿⣟⣛⣋⣩⣴⣾⣿⣿⣿⣿⢧⣿⣿⣿⠄⢀⡀⢀⡄⠄⠄⠄⠄⣼⣿⣿
⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠛⠻⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠛⠛⢁⣼⣿⡿⠃⠄⠑⠅⣾⠃⠄⠄⠄⠄⣿⣿⣿
⠄⠄⠄⣀⣄⡀⠄⠄⠄⠄⠄⠄⠄⠄⠄⠈⠉⠉⠛⠿⠿⣿⣿⠿⠿⠛⠋⠉⠧⠄⠄⠄⠄⣾⣿⣿⠁⢀⠂⠈⡢⢵⠄⠄⠄⠄⣸⣿⣿⣿
⠄⠄⠄⠿⣿⣿⣦⣄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠈⠡⢶⣆⠈⠂⠅⠘⠴⠒⠠⣀⣾⣿⣿⣿⣿

(Now) Same options without RGB control:
⣿⣿⢻⣿⣿⣿⣿⣿⣳⣿⣿⣿⣿⣿⣿⣿⣿⣯⣿⣿⣿⣽⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡏⣿⣿⣿⣷⣻⣿⣿⣿⣧⣹⣿⣿⣿⣿⣿
⣿⢧⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣿⣿⣿⣿⣿⣿⣿⣷⢿⣿⣏⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣽⣿⣿⣿⣿⣿⣫⣿⣿⣿⣿⣿⣷⣛⣿⣯⣴⣯⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⢘⠟⢾⣿⣿⣿⣻⣿⣿⣯⣿⢻⣿⣿⣿⣿
⣯⣿⣿⣿⣿⣾⣿⣿⣟⣻⡿⣻⣿⣿⣿⣯⣿⣿⣿⣷⢿⣿⢻⣾⣿⣿⣿⣿⣿⣿⣿⣿⢹⣿⠸⣽⣿⣿⣽⣿⠿⣿⣿⣻⣿⡿⣇⣿⣿⣿
⣼⣿⣿⣾⣿⣿⣿⣿⡿⣻⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣽⣏⣿⣿⣿⣿⣿⣿⣿⣿⣏⣿⢧⣿⣿⣿⣿⣿⣿⣿⣿⣧⣿⣿⣦⣿⣿⣿⣿
⣻⣿⣿⣿⣿⣿⣿⣿⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣸⣿⣿⣿⣿⣿⣿⣿⣻⣿⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣽⣿⣿⣿⣵⣻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⡿⠿⠛⠛⠛⠉⠛⠛⠻⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣿⣿⣾⣯⣾⣿⣿⣿⣿⣻⣿⡿⠿⠿⣿⣿⣿⣿⣿⣿⣿⣿⣟
⣿⣿⣿⣿⣿⣿⣿⡏⠄⠄⠄⠄⠄⠄⠄⠄⠄⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⠉⠄⠄⠄⠄⠄⢸⣿⣿⣿⡟⣿⡟⣼
⢻⣿⣿⣿⣿⣿⣿⣇⠄⠄⠄⠄⣀⠄⠄⠄⠄⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠄⠄⠄⠄⠄⠄⢀⣿⣿⣿⠹⢧⡼⣿
⡿⣿⣿⣿⣿⣿⣿⣿⣷⣾⣿⣿⣿⣿⣿⣶⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣤⣤⣤⣤⣤⣤⣸⣿⣿⣿⣖⣿⣿⣿
⣷⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣾⣿⣿⣞
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⣿⣿⣿
⣿⣟⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠋⠄⢿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⠄⠄⢸⣿⣿
⣿⣿⡿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠄⣀⣸⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⣿⣽⣷⣾⣿⣿⣿⣿
⣿⣿⣿⣷⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⣟⣿⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿
⠘⣿⣿⣿⣝⣿⣿⣿⣿⣿⣿⣿⣿⣻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⣿⣿⣿⢯⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⠄⠈⢹⣿⣿⣾⣿⣿⣿⣿⣿⣿⣿⣷⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢿⣳⣾⣿⣿⣻⣿⣿⣿⣿⣿⠟⢫⣿⣟⣿⣿⣿⣿⣿
⠄⠄⠄⢨⡿⣿⣔⢽⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢷⣿⣿⣿⡿⣳⡆⢀⣾⣿⣿⣧⣿⣿⣿⣿
⠄⠄⠄⣿⣿⣯⣟⢞⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠟⠛⢩⣾⣿⣿⡿⣰⣿⣟⣿⣿⣟⢿⣿⣿⣿⣿⣿
⠄⠄⠄⣿⣿⣿⣿⣿⣮⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠿⣿⣿⣿⡿⠿⠟⠋⠉⣿⠄⠄⠄⠄⣾⣿⣿⠏⢡⣿⣿⣮⢿⣿⣿⣷⣶⣿⣿⣿⣿
⠄⠄⠘⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠉⠹⣾⣖⡈⠿⣿⣿⣾⡞⢿⣯⣾⣿⣿⣿⣿
![image](https://user-images.githubusercontent.com/78324780/106400324-63ab2100-63fc-11eb-924e-c4358c7e62a4.png)

Image Source: 
![image](https://user-images.githubusercontent.com/78324780/106400199-cb14a100-63fb-11eb-8eee-f76a55e69d8e.png)

**Comment by 505e06b2** [comment]
It looks pretty okay with Dithering on:
⢜⢰⢡⢣⠪⡢⡱⡨⡢⡱⡸⠄⢂⢇⠪⡢⡱⡨⠂⠄⡀⠄⡕⢌⢆⢕⢕⢌⢆⢕⢌⢆⢕⢌⢆⢕⢌⢆⢕⢌⢆⢕⢌⡆⢇⠅⠄⠄⢑⢌⢆⢕⢌⢆⢗⢌⢆⢕⢌⢆⢕⢌
⠜⡔⡝⢔⢕⢱⢨⠢⣃⠎⠠⠐⠨⡢⢣⢱⢨⠊⠄⠂⠄⠄⢎⠪⡢⡱⢱⡱⡘⡔⢕⠜⡔⡱⡘⡔⢕⢸⢐⠕⡜⢔⢅⢇⢣⠃⠈⢀⠸⡐⡕⡌⢆⢣⠣⡣⡱⡘⡔⡱⡘⡔
⠜⡜⡜⢌⢆⢣⠪⡸⠠⠄⠄⠄⡕⢜⠌⣆⠃⠄⠂⠈⢀⠄⠈⡎⢜⢌⢎⢎⢎⢎⢎⢕⠜⡔⢕⢜⢸⠰⡑⢕⠅⡇⡮⡣⡱⠄⠈⠄⠄⢣⠪⡸⡘⡔⡕⠸⡨⢪⢘⢌⠪⡌
⢜⢪⢸⢨⠢⡣⡱⠁⠠⠄⠂⢠⢃⠇⡕⠂⡀⠁⡀⠁⡀⢀⠢⠸⡱⡑⡕⡅⢣⢱⢡⠣⡱⡸⢰⠡⡣⢱⢑⢕⢱⢑⡝⡎⡎⠄⡁⠈⠄⠸⡨⡢⠣⣊⠂⠨⡪⢪⠪⡸⡘⡌
⡪⢪⢢⠱⡡⠃⡁⠑⠐⠄⠆⡜⡔⡕⠅⠄⠄⠤⠐⠐⠈⠠⠄⠄⠘⣌⠪⢬⠄⢇⢎⠪⡢⢣⠱⡑⢕⠅⡇⡪⡊⡆⡇⡓⠄⡀⠈⠂⠅⢄⡣⡪⡑⡕⠈⠄⢪⢪⠣⡪⡘⡌
⡪⡊⢆⠇⠁⠄⠠⠐⠄⠄⢰⠱⠊⠄⠁⠐⠄⠄⠂⠁⠈⠄⠄⠐⠄⢀⠣⡣⡂⢀⢣⠱⡑⡅⢇⢣⠣⡱⢱⢸⢨⢪⠊⡀⠄⢀⠈⠄⠄⠄⢘⠔⡅⠇⠉⠈⢱⢱⢱⢡⠣⡪
⢰⠑⠁⡀⠂⠄⠂⠄⠄⠠⠃⠠⠄⠂⠁⢀⠁⠄⠄⠂⠁⠄⠂⠐⠈⠄⠄⠱⡱⠄⢀⢣⢱⠸⡘⡔⢕⢱⢡⢇⢣⠃⢀⠄⠠⠄⠄⠂⢀⠁⠄⡇⡎⠄⠐⠈⠄⡇⡇⡕⡱⡨
⠁⠄⡁⠄⡀⠁⡀⠁⠠⠐⠄⡀⠂⢀⠈⢀⠄⡂⡠⡀⠂⡁⠄⠂⠐⠈⠄⠄⠈⠃⠄⠱⡸⡘⡌⢎⠪⡢⡃⡇⡃⠠⠄⠐⠄⡀⠁⠐⠄⠄⠂⢕⠄⡈⠄⠄⠁⡎⡎⡜⢔⡑
⠄⠠⠄⠄⠄⠄⠄⠐⢀⠠⠄⡀⠄⠠⠄⠄⢀⠄⢀⠈⠁⠐⠄⡁⠄⠂⠐⠄⡀⢁⠄⠁⠑⡜⢌⢎⠪⠊⡨⠊⠄⡀⠐⠈⠄⠄⡨⠠⠈⠄⠂⠁⠄⡀⠄⠐⠄⢕⢕⢜⢔⡑
⠄⠠⠄⠐⠄⠐⠈⢀⠄⣀⢤⡴⣖⣷⣻⡾⣾⣺⢶⣔⣄⠁⢀⠈⢀⠈⡀⠄⠄⠄⠄⢁⠄⠱⡑⠜⠄⠐⠁⡀⠁⢀⠄⡊⠜⠈⠄⡐⣈⣀⡐⡈⠄⠄⡀⠄⠂⢕⢕⠜⡔⡜
⠄⠠⠄⠁⡀⠁⠠⠠⠊⢠⢷⣻⡯⣷⣻⡽⣯⣟⣯⢷⣻⠌⢄⠄⠠⠄⢀⠠⠐⠄⠈⠄⡀⠂⠁⢀⠐⠈⠄⡀⠈⠄⠈⢀⢔⣼⢯⡿⣷⢷⣿⢽⢧⠃⡀⠄⡀⢕⢅⠇⣮⢪
⡀⠄⠂⠁⠄⡠⠃⠄⡀⠼⡽⣺⢽⣳⣻⡺⣳⢽⣺⢽⡺⡅⠄⠢⠄⠂⠄⡀⠠⠄⢁⠠⠄⠠⠈⠄⢀⠄⠁⠄⠄⠁⠨⠊⡽⣞⡿⡯⡿⡽⣞⡿⣝⠆⠈⠄⠄⡕⣅⢗⠥⡑
⡂⠄⠠⠐⠄⠢⠄⢀⠄⣀⢛⠮⠓⠃⠃⠙⠘⠓⠕⢗⠽⠄⢀⠄⢁⠄⠁⢀⠄⠄⢀⠄⠄⠠⠐⠈⠄⠄⢁⠄⠂⢠⠃⠄⢝⢾⢽⢽⢽⢝⣗⢽⡪⠃⠄⡡⠄⡧⢇⠎⣇⠣
⡸⠄⠠⠄⠂⠈⢁⠄⡀⢀⠄⠠⠄⡈⢀⠁⠐⠄⠄⢀⠈⠁⠂⢀⠄⠄⠁⢀⠄⠄⠄⠄⠠⠄⠄⠄⠂⠁⠄⠠⠐⠄⢂⠄⠐⠉⡈⠠⠐⠄⡈⢈⠊⠄⠰⠄⠌⢘⠜⡌⢎⢎
⡸⡀⠐⠄⠂⠁⡀⠄⠠⠄⠂⢁⠠⠄⠄⢀⠁⠄⠂⠄⠁⠉⡈⠐⠄⠠⠐⠄⠄⠄⠂⠄⠄⠠⠐⠄⠂⠄⡁⠠⠄⠂⠄⠄⠈⡀⠄⠠⠐⠄⠠⠄⡀⠂⠐⠄⠄⡪⢪⠸⡘⡜
⢰⠱⠈⢀⠈⡀⠄⠐⠠⠈⡐⠄⠄⠂⠐⢀⠠⠄⠐⠈⠄⠁⢀⠄⢁⠄⠄⠄⡁⠄⠐⠄⠐⠄⠠⠐⠄⠁⠄⠠⠐⠈⠄⠐⠄⠄⢀⠂⡀⠡⠄⡁⠠⠄⡁⠐⢀⢧⠣⡱⡡⠣
⢪⢸⠠⠄⠄⢀⠂⠁⠄⡁⠄⡈⠄⠈⠄⠂⠄⠄⠁⡀⠁⠐⠄⠠⠄⠠⠄⠂⠄⠈⡀⠈⡀⠈⢀⠠⠐⠈⠄⠄⠄⠂⠈⡀⢁⠐⠄⠄⠐⡀⠁⠄⠂⠠⠄⠂⡸⡜⡎⡪⡨⡱
⢊⠆⡇⡀⠂⠠⠄⠡⠐⠄⠄⢀⠂⠁⡀⠂⠁⠠⠄⠄⠈⢀⠈⢀⠄⠂⠄⠂⠈⠄⡀⠄⠄⡈⠄⠄⡀⠄⠂⠠⠈⠄⢁⠄⠄⠄⠅⠈⠄⠂⠁⠄⢁⠐⠈⢀⢗⡝⣎⢪⠸⡐
⢊⢪⠸⡀⠐⠄⠁⠄⠂⠐⠈⠄⡀⠂⠄⠄⠁⠠⠐⠄⠈⠄⡀⠠⠄⠂⠁⠄⡁⢀⠄⠠⠄⠠⠄⠁⠄⢀⠠⠄⠂⠁⢀⠠⠄⢁⠄⡁⠐⠈⡀⢈⠄⠠⠈⢰⢳⡹⡜⡔⢕⡑
⢊⢎⠪⡢⠈⠄⢁⠠⠐⠈⠄⠂⠄⠄⠁⠄⠂⠠⠐⠄⠁⠠⠄⠠⠄⠂⠄⠁⠄⡀⠄⠂⠄⠂⢀⠈⢀⠄⡀⠠⠐⠈⠄⢀⠠⠄⠄⠄⠂⠁⠄⡀⠄⠂⠄⣗⢵⠝⠮⠪⠪⠬
⢊⢆⢣⢩⠂⠁⢀⠄⠠⠐⠄⢈⠄⠄⠈⢀⠁⠠⠄⠂⠁⢀⠐⠄⠐⠄⠁⠈⢀⠄⠄⠁⢀⠁⢀⠠⠄⢀⠄⠄⠄⠄⠂⠄⡀⠄⠐⠈⠄⠄⠁⠄⣀⠤⠒⠁⡁⠐⠄⠄⠠⠄
⢪⢘⢌⢆⢃⠈⠄⠄⠄⠄⠂⢀⠠⠄⡨⠐⠠⢀⠐⠄⠐⠄⡀⠈⡀⠈⠄⠁⡀⠄⠄⠂⠄⠠⠄⠄⠄⠄⠄⠄⠂⠄⠄⠁⠄⡀⠄⠂⡀⠤⠒⠉⠄⠄⡀⠄⠄⠐⠄⠐⠄⡀
⡪⡸⢰⠡⡣⡂⠈⢀⠐⠈⠄⡀⢀⠄⠐⡀⠄⡀⠁⠢⡁⠄⠠⠄⠠⠈⠄⠁⢀⠠⠄⠐⠈⠄⡀⠁⠄⠂⠠⠈⠄⠂⠄⠂⠁⢀⠔⠈⢀⠄⠠⠄⠂⠁⡀⢀⠈⠄⢁⠄⠁⠄
⡕⡧⡱⡑⢕⢸⠄⡀⠠⠐⠄⢀⠄⡀⠁⠈⠢⡐⢀⠄⠄⠑⠠⢂⢀⠐⠈⠄⡀⠄⠄⠂⠄⠁⢀⠄⠁⠄⠂⣀⠝⠄⠁⠠⠠⠃⠄⠠⠄⠠⠄⡐⠠⠡⠘⡄⠄⠈⢀⠄⢈⠄
⣫⡺⡵⡸⡘⢬⠱⡀⡀⠠⠐⠄⢀⠠⠄⠁⡀⠈⠂⢄⠐⠄⢀⠄⠄⠁⠂⠃⠄⠤⠠⠠⠡⠨⠠⠠⠁⢂⠅⠊⠄⠠⠈⢠⠃⠄⠂⠄⠂⠄⣂⡢⣕⠋⡑⠱⡀⢁⠄⠠⠄⠄
⡳⣝⢮⡫⡇⡇⡕⢕⠕⠢⡂⡄⡀⠄⠄⠂⠄⠄⠁⢀⠠⠈⠐⠐⠨⠠⠠⢀⢀⠠⡀⠄⠤⠐⠂⠁⠁⡀⠄⠂⠁⠠⠰⠁⠄⡀⠂⠡⡑⠉⡮⡺⠁⡐⠨⢐⢩⢂⠐⠄⠄⠁
⣪⢯⡳⣝⠆⠌⠪⡪⢪⣂⠢⠨⢘⠰⡀⠄⠐⠄⠐⠄⢀⠄⠂⠁⢀⠐⠄⠄⠄⠄⠄⠄⠠⠄⠂⠈⠄⡀⠈⢀⣐⢤⠃⠄⠂⠄⠠⣱⠃⠄⢕⠁⠠⢂⢑⢐⠰⡡⠄⠄⠠⠄
⢗⣗⢽⢵⠡⢈⠢⠨⠑⢜⢔⢁⢂⠂⠌⢌⠑⠢⠡⣀⠠⠄⠐⠈⠄⠄⠄⠂⠄⠂⠄⠂⡀⠐⣀⢨⡠⣒⡎⣗⢮⠃⠄⠐⠄⡁⣕⠅⢀⠰⡁⠠⠨⠠⢑⠢⠬⡆⠠⠄⠄⠄
⡗⣗⣝⠮⠄⠂⠈⠄⡑⡐⠨⠡⢐⠨⠨⢐⠨⢈⢂⠂⠅⠍⡐⡶⣪⢔⡤⣔⢬⣢⢳⡲⡲⡽⡬⣢⢞⡞⣞⢮⣫⠄⠈⣀⢖⢜⠌⠄⢀⠄⢑⠦⡁⠅⡂⠌⡤⠃⠄⠠⠐⠄
⣏⢾⢜⡗⡄⠂⠐⠄⡀⠂⠅⢊⠐⠨⢐⢐⠨⢐⠐⠨⠨⢐⠠⢹⢮⡳⣝⢮⡳⣳⢝⡮⣻⡪⡯⡮⣳⢝⡮⣳⡳⣝⢭⡀⠄⠑⢝⢆⡀⠄⠘⠄⢈⢢⠤⠃⠄⠠⠐⠄⠠⠄

While I really don't feel that fine tuning the average is beneficial, I can see the need for several different [greyscaling algorithms](https://docs.gimp.org/en/gimp-filter-desaturate.html).
