### ISSUE TITLE
RGB options. Please bring it back!

### ISSUE THREAD

**Issue by TomaQToma** [505e06b2/Image-to-Braille#4]
I used to love how this braille converter was the only one who was able to adjust the RGB levels, now without the option, smaller convertions and images with similar color pallet just don't work anymore, also the convertions aren't as precise and neat after the removal of the RGB option. Hope you bring it back again.

**Comment by 505e06b2** [comment]
As I said in #3 , this tool is for converting existing images to 1-bit braille via very basic greyscaling algorithms. Personally, when I convert an image I either leave it as-is, and use Dithering, or alter the image in a bitmap editor to improve clarity. I was typically disappointed when I used the RGB controls and they only existed as temporary measure to improve the output before dithering was implemented.

That said, I believe the rewrite I've recently made to the entire project will make works based on this much easier - please feel free to fork this project and implement a more complex frontend.
